name: Bug反馈
description: 创建一个反馈来帮助我们对脚本进行改进。
labels: ["bug"]
assignees: andywang425

body:
  - type: markdown
    attributes:
      value: |
        # 欢迎
        你可能可以在本项目的[README](https://github.com/andywang425/BLTH/blob/master/README.md)，脚本的内置说明或[已存在的issue](https://github.com/andywang425/BLTH/issues)中找到答案。
        若不能，请按要求编写反馈信息。

  - id: describe
    type: textarea
    validations:
      required: true
    attributes:
      label: "描述bug"
      description: |
        简要描述所遇到的bug。
      placeholder: |
        例子: 每日登录任务无法完成，任务状态显示为红色的叉且控制台中有相关报错。

  - id: reproduction
    type: textarea
    validations:
      required: true
    attributes:
      label: "重现bug"
      description: |
        说明您在进行了怎样的操作后出现了bug。
      placeholder: |
        例子：
        1. 开启每日登录功能
        2. 刷新页面
        3. ...

  - id: expection
    type: textarea
    validations:
      required: true
    attributes:
      label: "预期行为"
      description: |
        简要描述进行以上操作后预期的脚本行为。
      placeholder: |
        例子: 完成每日登录任务。

  - id: picture
    type: textarea
    validations:
      required: false
    attributes:
      label: "截图"
      description: |
        如果可以，请提供有关截图。
      placeholder: |
        截图后在此处 ctrl + v 黏贴即可。

  - id: log
    type: textarea
    validations:
      required: true
    attributes:
      label: "运行日志"
      description: |
        控制台日志的查看方式在README中[使用](https://github.com/andywang425/BLTH/blob/master/README.md#使用)这一节里有提到。
        需要注意的是部分报错不会带有BLTH字样。
      placeholder: |
        请在此黏贴运行日志。截图或文字皆可。

  - id: system
    type: input
    validations:
      required: true
    attributes:
      label: "操作系统"
      description: |
        请给出你使用的操作系统名称和版本号。
      placeholder: |
        例子: Windows 10

  - id: browser
    type: input
    validations:
      required: true
    attributes:
      label: "浏览器"
      description: |
        请给出你使用的浏览器名称和版本号。
      placeholder: |
        例子: Chrome 115.0.5790.102

  - id: userscript_manager
    type: input
    validations:
      required: true
    attributes:
      label: "用户脚本管理器"
      description: |
        请给出你使用的用户脚本管理器名称和版本号。
      placeholder: |
        例子: Tampermonkey 4.19.0

  - id: BLTH_version
    type: input
    validations:
      required: true
    attributes:
      label: "脚本版本号"
      description: |
        你使用的BLTH的版本。可以在用户脚本管理器中查看。
      placeholder: |
        例子: 7.0.0

  - id: network_condition
    type: dropdown
    validations:
      required: true
    attributes:
      label: "网络情况"
      description: |
        可以理解为网速情况。
      options:
        - 好
        - 一般
        - 坏

  - id: other_scripts
    type: input
    validations:
      required: false
    attributes:
      label: "其他浏览器拓展/用户脚本"
      description: |
        在此写上您认为可能会对本脚本产生影响的浏览器拓展/用户脚本。
      placeholder: |
        例子: adblock

  - id: extra
    type: textarea
    validations:
      required: false
    attributes:
      label: "其他"
      description: |
        若您有其他想要补充的内容，请在此说明。

  - type: markdown
    attributes:
      value: |
        # 感谢反馈！
        我们会尽快回复您提出的issue。
